spring.application.name=security

#spring.security.user.name=user
#spring.security.user.password=test

spring.datasource.url=jdbc:mysql://localhost:3306/test
spring.datasource.username=root
spring.datasource.password=05102005

spring.jpa.show-sql=true